export const GET_PEOPLE_START = "GET_PEOPLE_START";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const DELETE_PEOPLE = "DELETE_PEOPLE";
export const ADD_PEOPLE = "ADD_PEOPLE";
export const IS_AUTH = "IS_AUTH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_SINGLE_PEOPLE = "GET_SINGLE_PEOPLE";
export const UPDATE_PEOPLE = "UPDATE_PEOPLE";
export const CLEAR_DATA = "CLEAR_DATA";
//for localStorage
export const GET_PEOPLE_LIST = "GET_PEOPLE_LIST";
export const ADD_PEOPLE_LIST = "ADD_PEOPLE_LIST";
export const DELETE_PEOPLE_LIST = "DELETE_PEOPLE_LIST";
export const UPDATE_PEOPLE_LIST = "UPDATE_PEOPLE_LIST";
export const REPEATED_VALUE_VALIDATION = "REPEATED_VALUE_VALIDATION";
export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
//for sorting
export const PEOPLE_AFTER_SORTED = "PEOPLE_AFTER_SORTED";
